name: unit-tests

on:
  push:
    branches:
      - "**"

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.x
          cache: npm
          cache-dependency-path: "./backend/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: test
        run: npm run test

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.x
          cache: npm
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: test
        run: npm run test

  test-global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: test
        run: npm run test:lint && npm run test:unit
